#!/usr/bin/env sh
set -eu
if command -v systemctl >/dev/null 2>&1; then
    systemctl stop openvino-oneapi-system.service >/dev/null 2>&1 || true
    systemctl disable openvino-oneapi-system.service >/dev/null 2>&1 || true
fi
exit 0
