# Generated by Django 6.0.1 on 2026-01-23 18:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('completed_quantity', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=3)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('controller_type', models.CharField(choices=[('FANUC', 'Fanuc'), ('SIEMENS', 'Siemens'), ('HEIDENHAIN', 'Heidenhain'), ('HAAS', 'Haas')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('axes', models.IntegerField(default=3)),
                ('max_rpm', models.IntegerField(default=12000)),
                ('work_envelope', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('ENDMILL', 'Endmill'), ('DRILL', 'Drill'), ('BORE', 'Boring Bar'), ('FACE', 'Face Mill'), ('THREAD', 'Thread Mill')], max_length=20)),
                ('diameter', models.FloatField()),
                ('length', models.FloatField()),
                ('material', models.CharField(choices=[('HSS', 'High Speed Steel'), ('HSS_CO', 'HSS-Cobalt'), ('CARBIDE', 'Carbide'), ('CERAMIC', 'Ceramic'), ('PCD', 'Polycrystalline Diamond')], max_length=20)),
                ('coating', models.CharField(blank=True, max_length=50)),
                ('expected_life', models.IntegerField()),
                ('current_usage', models.IntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_USE', 'In Use'), ('WORN', 'Worn'), ('BROKEN', 'Broken')], default='NEW', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RiseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('ENGINEER', 'Design Engineer'), ('OPERATOR', 'Machine Operator'), ('AUDITOR', 'Quality Auditor')], default='OPERATOR', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='erp.organization')),
            ],
            options={
                'permissions': [('can_override_safety', 'Can override safety limits'), ('can_view_economics', 'Can view cost analytics'), ('can_manage_tools', 'Can manage tool inventory')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=100)),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('measured_dimensions', models.JSONField()),
                ('specified_dimensions', models.JSONField()),
                ('passed', models.BooleanField()),
                ('non_conformances', models.JSONField(default=list)),
                ('root_cause_analysis', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.job')),
            ],
        ),
        migrations.CreateModel(
            name='EconomicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_time_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tool_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cycle_time', models.FloatField()),
                ('cost_per_part', models.DecimalField(decimal_places=2, max_digits=10)),
                ('traditional_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.machine'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('TOOL_REPLACEMENT', 'Tool Needs Replacement'), ('SAFETY', 'Safety Alert'), ('QUALITY', 'Quality Issue'), ('MAINTENANCE', 'Maintenance Required'), ('MATERIAL', 'Material Low Stock')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization'),
        ),
        migrations.CreateModel(
            name='ConfigurationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_type', models.CharField(max_length=50)),
                ('config', models.JSONField()),
                ('values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('gcode', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(max_length=50)),
                ('complexity_score', models.FloatField()),
                ('estimated_cycle_time', models.FloatField()),
                ('dimensions', models.JSONField(default=dict)),
                ('llm_suggestions', models.JSONField(default=dict)),
                ('actual_cycle_time', models.FloatField(null=True)),
                ('quality_score', models.FloatField(null=True)),
                ('success', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.project'),
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('rpm', models.IntegerField()),
                ('load', models.FloatField()),
                ('vibration_x', models.FloatField()),
                ('vibration_y', models.FloatField()),
                ('vibration_z', models.FloatField()),
                ('spindle_temp', models.FloatField()),
                ('coolant_temp', models.FloatField(null=True)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('position_z', models.FloatField()),
                ('dopamine', models.FloatField()),
                ('cortisol', models.FloatField()),
                ('signal', models.CharField(max_length=10)),
                ('active_tool', models.CharField(max_length=10)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.machine')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', '-timestamp'], name='erp_telemet_machine_405c1e_idx')],
            },
        ),
    ]
